package com.example.marvelcodetest.core

import com.example.marvelcodetest.di.DaggerAppComponent
import dagger.android.AndroidInjector
import dagger.android.DispatchingAndroidInjector
import dagger.android.support.DaggerApplication
import javax.inject.Inject

class MainApplication: DaggerApplication() {

    /**
     * Tell Dagger which [AndroidInjector] to use - in our case
     * [com.google.samples.apps.iosched.di.AppComponent]. `DaggerAppComponent`
     * is a class generated by Dagger based on the `AppComponent` class.
     */

    @Inject
    lateinit var dispatchingServiceInjector: DispatchingAndroidInjector<Any>

    override fun applicationInjector(): AndroidInjector<out DaggerApplication> {
        return DaggerAppComponent.builder().create(this)
    }

    override fun androidInjector(): AndroidInjector<Any> {
        return dispatchingServiceInjector
    }

    override fun onCreate() {
        super.onCreate()
    }

}